# Generated by Django 5.2 on 2025-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_word"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="word",
            name="giphyURL",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="word",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
