# Generated by Django 5.2 on 2025-05-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0003_alter_word_options_word_giphyurl_word_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="word",
            new_name="word_text",
        ),
    ]
