# Generated by Django 5.2 on 2025-05-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0004_rename_word_word_word_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="sentence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="api_app.sentence",
            ),
        ),
    ]
