# Generated by Django 5.2 on 2025-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0005_alter_word_sentence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={},
        ),
        migrations.RemoveField(
            model_name="word",
            name="order",
        ),
        migrations.AlterField(
            model_name="word",
            name="giphyURL",
            field=models.TextField(blank=True),
        ),
    ]
